//CORS:CROSS ORIGIN RESOURCE SHARING
//What is Cross Origin?
//IT IS A MECHANISM WHERE TWO WEBAPPS(WEBAPPS SHOULD BE IN DIFFERENT ORIGIN)
//SHARE RESOURCES USING ADDITIONAL HTTP HEADERS

//GOURAB.IN WANTS TO REQUEST DATA FROM EXTERNAL DOMAINS LIKE FROM GOOGLE.COM/API/GETDATA --THIS WAS NEVER ALLOWED
//GOURAB.IN WANTS TO REQUEST DATA FROM SUB-DOMAINS LIKE API.GOURAB.IN--THIS WAS NEVER ALLOWED
//GOURAB.IN:80 WANTS TO REQUEST DATA FROM GOURAB.IN:5050--THIS WAS NOT ALLOWED
//HTTP://GOURAB.IN WANTS TO REQUEST DATA FROM HTTPS://GOURAB.IN--THIS WAS NOT ALLOWED

//BUT AFTER CORS THIS HAS BEEN MADE POSSIBLE
